export const FETCH_GIFS = 'FETCH_GIFS';
export const FETCH_GIFS_SUCCESS = 'FETCH_GIFS_SUCCESS';
export const FETCH_GIFS_FAILURE = 'FETCH_GIFS_FAILURE';

export const SEARCH_GIFS = 'SEARCH_GIFS';
export const SEARCH_GIFS_SUCCESS = 'SEARCH_GIFS_SUCCESS';
export const SEARCH_GIFS_FAILURE = 'SEARCH_GIFS_FAILURE';
